{{- if .Values.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sso-bridge-reconciler
  namespace: {{ .Release.Namespace }}
  labels:
    catalyst.openova.io/blueprint: bp-sso-bridge
    app.kubernetes.io/name: sso-bridge-reconciler
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
