// StepComponents — unified bp-<x> marketplace card grid.
//
// Replaces the previous 9-block category-grouped checkbox tree (PILOT, SPINE,
// SURGE, …) with a flat marketplace card grid driven by the unified
// `bp-<name>` Blueprint surface every Catalyst Application has.
//
// Per docs/INVIOLABLE-PRINCIPLES.md #2 ("never compromise from quality") and
// the Pass 103 / 104 unification: every installable thing is a Blueprint.
// Application = `bp-<name>` shape regardless of category, regardless of
// caller (corporate provisioning, SME marketplace, franchised Sovereign
// admin). One catalog, one selection model, one card surface.
//
// Visibility filter (mandatory):
//   - listed   → renders as a card; user opts in/out
//   - unlisted → mandatory infra (cilium, flux, crossplane, openbao,
//                cert-manager, …) auto-installed by the bootstrap kit and
//                NEVER appears in this grid
//   - private  → org-private, not part of public catalog
//
// Data source: src/shared/constants/catalog.generated.ts (auto-generated by
// scripts/build-catalog.mjs from every platform/<name>/blueprint.yaml +
// products/<name>/blueprint.yaml in the monorepo). Re-run `npm run
// build:catalog` after editing any blueprint.yaml; both `npm run dev` and
// `npm run build` invoke it automatically.
//
// Card visual: mirrors core/marketplace/src/components/AppsStep.svelte —
// horizontal logo + title + summary + chips, click-to-toggle, selected
// state with success-color border + status corner chip. Same family as the
// SME marketplace product so users moving between the two recognise it.

import { useMemo, useState } from 'react'
import { Search, Plus, Check, Info } from 'lucide-react'
import { useWizardStore } from '@/entities/deployment/store'
import { LISTED_BLUEPRINTS, LISTED_CATEGORIES, type BlueprintCardEntry } from '@/shared/constants/catalog.generated'
import { useBreakpoint } from '@/shared/lib/useBreakpoint'
import { StepShell, useStepNav } from './_shared'

/** Sort order: selected first (preserves cart-like UX from marketplace), then by title. */
function sortBlueprints(items: readonly BlueprintCardEntry[], selected: ReadonlySet<string>): BlueprintCardEntry[] {
  return [...items].sort((a, b) => {
    const aSel = selected.has(a.id) ? 0 : 1
    const bSel = selected.has(b.id) ? 0 : 1
    if (aSel !== bSel) return aSel - bSel
    return a.title.localeCompare(b.title)
  })
}

/** Letter-pill fallback when a Blueprint's card.icon is null (most current entries). */
function IconFallback({ title }: { title: string }) {
  const letter = (title[0] ?? '?').toUpperCase()
  // Hash to a stable colour from the title so each Blueprint gets its own tile.
  let hash = 0
  for (let i = 0; i < title.length; i++) hash = (hash * 31 + title.charCodeAt(i)) | 0
  const hue = Math.abs(hash) % 360
  return (
    <span
      aria-hidden
      style={{
        alignSelf: 'stretch',
        aspectRatio: '1 / 1',
        height: 'auto',
        borderRadius: 10,
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        flexShrink: 0,
        color: '#fff',
        fontSize: '1.2rem',
        fontWeight: 700,
        background: `oklch(58% 0.12 ${hue})`,
      }}
    >
      {letter}
    </span>
  )
}

function CardChip({ label, tone = 'neutral' }: { label: string; tone?: 'success' | 'neutral' | 'accent' }) {
  const palette = {
    success: { bg: 'rgba(74,222,128,0.14)', fg: '#4ADE80' },
    neutral: { bg: 'rgba(148,163,184,0.14)', fg: 'var(--wiz-text-md)' },
    accent: { bg: 'rgba(56,189,248,0.14)', fg: '#38BDF8' },
  }[tone]
  return (
    <span
      style={{
        display: 'inline-flex',
        alignItems: 'center',
        padding: '0.1rem 0.45rem',
        borderRadius: 999,
        fontSize: '0.65rem',
        fontWeight: 600,
        lineHeight: 1.4,
        whiteSpace: 'nowrap',
        background: palette.bg,
        color: palette.fg,
      }}
    >
      {label}
    </span>
  )
}

function BlueprintCard({ entry, selected, onToggle }: { entry: BlueprintCardEntry; selected: boolean; onToggle: () => void }) {
  return (
    <button
      type="button"
      onClick={onToggle}
      aria-pressed={selected}
      style={{
        position: 'relative',
        background: selected ? 'color-mix(in srgb, #4ADE80 6%, var(--wiz-bg-sub))' : 'var(--wiz-bg-sub)',
        border: selected ? '1.5px solid #4ADE80' : '1.5px solid var(--wiz-border-sub)',
        borderRadius: 12,
        padding: '0.6rem',
        display: 'flex',
        alignItems: 'stretch',
        gap: '0.75rem',
        cursor: 'pointer',
        transition: 'transform 0.15s, border-color 0.15s, background 0.15s',
        color: 'inherit',
        textAlign: 'left',
        font: 'inherit',
        height: 108,
        overflow: 'hidden',
      }}
    >
      <IconFallback title={entry.title} />

      <div style={{
        flex: 1,
        minWidth: 0,
        display: 'flex',
        flexDirection: 'column',
        gap: '0.25rem',
        paddingRight: '4.5rem',
        overflow: 'hidden',
      }}>
        <div style={{ display: 'flex', alignItems: 'baseline', gap: '0.5rem' }}>
          <span style={{
            color: 'var(--wiz-text-hi)',
            fontSize: '0.92rem',
            fontWeight: 600,
            lineHeight: 1.2,
            overflow: 'hidden',
            textOverflow: 'ellipsis',
            whiteSpace: 'nowrap',
            flex: '1 1 auto',
            minWidth: 0,
          }}>{entry.title}</span>
          {entry.category && (
            <span style={{
              color: 'var(--wiz-text-sub)',
              fontSize: '0.68rem',
              textTransform: 'capitalize',
              background: 'var(--wiz-border-sub)',
              padding: '0.1rem 0.4rem',
              borderRadius: 3,
              flexShrink: 0,
            }}>
              {entry.category}
            </span>
          )}
        </div>
        <p style={{
          margin: 0,
          color: 'var(--wiz-text-md)',
          fontSize: '0.78rem',
          lineHeight: 1.45,
          display: '-webkit-box',
          WebkitLineClamp: 2,
          WebkitBoxOrient: 'vertical',
          overflow: 'hidden',
        }}>
          {entry.summary || entry.tagline || 'No summary provided.'}
        </p>
        <div style={{ marginTop: '0.25rem', display: 'flex', flexWrap: 'nowrap', gap: '0.25rem', overflow: 'hidden', minHeight: '1.4rem' }}>
          <CardChip label="FREE" tone="success" />
          {entry.tags.slice(0, 2).map(t => (
            <CardChip key={t} label={t} tone="neutral" />
          ))}
          {entry.depends.length > 0 && (
            <CardChip label={`+ ${entry.depends.length} dep${entry.depends.length > 1 ? 's' : ''}`} tone="accent" />
          )}
        </div>
      </div>

      {/* Selected status corner (matches marketplace AppsStep.svelte) */}
      {selected && (
        <div style={{ position: 'absolute', bottom: '0.5rem', right: '0.55rem', pointerEvents: 'none' }}>
          <span style={{
            display: 'inline-flex',
            alignItems: 'center',
            gap: '0.3rem',
            padding: '0.15rem 0.55rem',
            borderRadius: 999,
            fontSize: '0.65rem',
            fontWeight: 600,
            lineHeight: 1.4,
            letterSpacing: '0.03em',
            background: 'rgba(74,222,128,0.16)',
            color: '#4ADE80',
          }}>
            <span style={{ width: 6, height: 6, borderRadius: '50%', background: 'currentColor', display: 'inline-block' }} />
            SELECTED
          </span>
        </div>
      )}

      {/* Add/remove circle button (top-right) */}
      <span
        aria-hidden
        style={{
          position: 'absolute',
          top: '0.6rem',
          right: '0.6rem',
          width: 32,
          height: 32,
          borderRadius: '50%',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          background: selected ? '#4ADE80' : 'rgba(56,189,248,0.85)',
          color: '#fff',
          boxShadow: '0 1px 4px rgba(0,0,0,0.2)',
        }}
      >
        {selected ? <Check size={16} strokeWidth={3} /> : <Plus size={16} strokeWidth={2.5} />}
      </span>
    </button>
  )
}

/**
 * Empty-state panel. Today (Pass 105), 0 of the 10 published blueprint.yaml
 * files have visibility:listed (every published one is mandatory infra). The
 * panel explains why the grid is empty and points at the doc that controls
 * what shows up here. As soon as a Blueprint with `visibility: listed`
 * lands in `platform/<name>/blueprint.yaml` (or `products/<name>/`), it
 * appears here on the next build with no code change required.
 */
function EmptyState() {
  return (
    <div style={{
      borderRadius: 12,
      border: '1.5px dashed var(--wiz-border-sub)',
      background: 'var(--wiz-bg-xs)',
      padding: '2rem 1.5rem',
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      gap: '0.75rem',
      textAlign: 'center',
    }}>
      <Info size={24} style={{ color: 'var(--wiz-text-sub)' }} aria-hidden />
      <h3 style={{ margin: 0, fontSize: '1rem', color: 'var(--wiz-text-hi)', fontWeight: 600 }}>
        No marketplace Blueprints published yet
      </h3>
      <p style={{ margin: 0, fontSize: '0.85rem', color: 'var(--wiz-text-sub)', maxWidth: 520, lineHeight: 1.55 }}>
        Mandatory infrastructure (Cilium, Flux, Crossplane, OpenBao, …) is installed by the bootstrap kit
        regardless of selection. Application Blueprints with <code style={{ background: 'var(--wiz-border-sub)', padding: '0.05rem 0.3rem', borderRadius: 3 }}>visibility: listed</code> appear
        here automatically. Every Application is the same <code style={{ background: 'var(--wiz-border-sub)', padding: '0.05rem 0.3rem', borderRadius: 3 }}>bp-&lt;name&gt;</code> shape — no special cases per category.
      </p>
      <p style={{ margin: 0, fontSize: '0.78rem', color: 'var(--wiz-text-hint)' }}>
        See <code>docs/BLUEPRINT-AUTHORING.md §1</code> for how to publish a Blueprint.
      </p>
    </div>
  )
}

export function StepComponents() {
  const { next, back } = useStepNav()
  const store = useWizardStore()
  const bp = useBreakpoint()

  const [query, setQuery] = useState('')
  const [activeCategory, setActiveCategory] = useState<string | null>(null)

  const selectedSet = useMemo(() => new Set(store.selectedBlueprints), [store.selectedBlueprints])

  const visible = useMemo(() => {
    let result = LISTED_BLUEPRINTS.slice()
    if (activeCategory) {
      result = result.filter(b => b.category === activeCategory)
    }
    if (query) {
      const q = query.toLowerCase()
      result = result.filter(
        b =>
          b.title.toLowerCase().includes(q) ||
          b.slug.toLowerCase().includes(q) ||
          b.summary.toLowerCase().includes(q) ||
          (b.category ?? '').toLowerCase().includes(q),
      )
    }
    return sortBlueprints(result, selectedSet)
  }, [query, activeCategory, selectedSet])

  const cols = bp === 'mobile' ? '1fr' : bp === 'tablet' ? '1fr 1fr' : 'repeat(3, minmax(0, 1fr))'

  return (
    <StepShell
      title="Applications"
      description={`Pick the Blueprints to install on the new Sovereign. Mandatory infrastructure (Cilium, Flux, Crossplane, OpenBao, cert-manager, …) is installed automatically by the bootstrap kit and is not shown here. Every selection is a unified bp-<name> Blueprint, regardless of category.`}
      onNext={next}
      onBack={back}
    >
      {/* Summary bar */}
      <div style={{ display: 'flex', alignItems: 'center', gap: 10, padding: '8px 12px', borderRadius: 8, background: 'rgba(56,189,248,0.05)', border: '1px solid rgba(56,189,248,0.12)' }}>
        <span style={{ fontSize: 12, color: 'var(--wiz-accent)', fontWeight: 600 }}>
          {store.selectedBlueprints.length} of {LISTED_BLUEPRINTS.length} Blueprints selected
        </span>
        <div style={{ flex: 1, height: 3, borderRadius: 2, background: 'var(--wiz-border-sub)', overflow: 'hidden' }}>
          <div
            style={{
              height: '100%',
              width: LISTED_BLUEPRINTS.length === 0
                ? '0%'
                : `${(store.selectedBlueprints.length / LISTED_BLUEPRINTS.length) * 100}%`,
              background: 'linear-gradient(90deg, #38BDF8, #818CF8)',
              transition: 'width 0.3s',
            }}
          />
        </div>
      </div>

      {LISTED_BLUEPRINTS.length === 0 ? (
        <EmptyState />
      ) : (
        <>
          {/* Toolbar */}
          <div style={{
            background: 'var(--wiz-bg-xs)',
            border: '1px solid var(--wiz-border-sub)',
            borderRadius: 12,
            padding: '0.75rem 1rem',
            display: 'flex',
            flexDirection: 'column',
            gap: '0.65rem',
          }}>
            <div style={{ position: 'relative' }}>
              <Search
                size={14}
                aria-hidden
                style={{
                  position: 'absolute',
                  left: 12,
                  top: '50%',
                  transform: 'translateY(-50%)',
                  color: 'var(--wiz-text-sub)',
                  opacity: 0.5,
                }}
              />
              <input
                type="search"
                placeholder={`Search ${LISTED_BLUEPRINTS.length} Blueprints…`}
                value={query}
                onChange={e => setQuery(e.target.value)}
                style={{
                  width: '100%',
                  padding: '0.6rem 0.85rem 0.6rem 2.2rem',
                  background: 'var(--wiz-bg-sub)',
                  border: '1px solid var(--wiz-border-sub)',
                  borderRadius: 8,
                  color: 'var(--wiz-text-hi)',
                  font: 'inherit',
                  fontSize: '0.88rem',
                }}
              />
            </div>
            {LISTED_CATEGORIES.length > 0 && (
              <div style={{ display: 'flex', flexWrap: 'wrap', gap: '0.35rem' }}>
                <button
                  type="button"
                  onClick={() => setActiveCategory(null)}
                  style={{
                    padding: '0.4rem 0.7rem',
                    borderRadius: 999,
                    background: activeCategory === null ? 'var(--wiz-accent)' : 'var(--wiz-bg-sub)',
                    border: '1px solid ' + (activeCategory === null ? 'var(--wiz-accent)' : 'var(--wiz-border-sub)'),
                    color: activeCategory === null ? '#fff' : 'var(--wiz-text-sub)',
                    font: 'inherit',
                    fontSize: '0.78rem',
                    cursor: 'pointer',
                    transition: 'all 0.15s',
                  }}
                >
                  All
                </button>
                {LISTED_CATEGORIES.map(cat => (
                  <button
                    key={cat}
                    type="button"
                    onClick={() => setActiveCategory(activeCategory === cat ? null : cat)}
                    style={{
                      padding: '0.4rem 0.7rem',
                      borderRadius: 999,
                      background: activeCategory === cat ? 'var(--wiz-accent)' : 'var(--wiz-bg-sub)',
                      border: '1px solid ' + (activeCategory === cat ? 'var(--wiz-accent)' : 'var(--wiz-border-sub)'),
                      color: activeCategory === cat ? '#fff' : 'var(--wiz-text-sub)',
                      font: 'inherit',
                      fontSize: '0.78rem',
                      cursor: 'pointer',
                      transition: 'all 0.15s',
                      textTransform: 'capitalize',
                    }}
                  >
                    {cat}
                  </button>
                ))}
              </div>
            )}
          </div>

          {/* Section head */}
          <div style={{
            display: 'flex',
            justifyContent: 'space-between',
            alignItems: 'baseline',
            paddingBottom: '0.4rem',
            borderBottom: '1px solid var(--wiz-border-sub)',
          }}>
            <h3 style={{ color: 'var(--wiz-text-hi)', fontSize: '0.95rem', margin: 0, fontWeight: 600 }}>
              Marketplace Blueprints
            </h3>
            <span style={{ color: 'var(--wiz-text-sub)', fontSize: '0.78rem' }}>
              {visible.length} shown · {store.selectedBlueprints.length} selected
            </span>
          </div>

          {/* Card grid — mirrors core/marketplace/AppsStep.svelte layout */}
          <div style={{ display: 'grid', gridTemplateColumns: cols, gap: '0.65rem' }}>
            {visible.map(entry => (
              <BlueprintCard
                key={entry.id}
                entry={entry}
                selected={selectedSet.has(entry.id)}
                onToggle={() => store.toggleBlueprint(entry.id)}
              />
            ))}
            {visible.length === 0 && (
              <p style={{
                gridColumn: '1 / -1',
                color: 'var(--wiz-text-sub)',
                fontSize: '0.85rem',
                textAlign: 'center',
                padding: '2rem',
              }}>
                No Blueprints match your filters.
              </p>
            )}
          </div>
        </>
      )}
    </StepShell>
  )
}
