apiVersion: apps/v1
kind: Deployment
metadata:
  name: listmonk
  namespace: apps
  labels:
    app: listmonk
    openova.io/tenant: "aaa"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: listmonk
  template:
    metadata:
      labels:
        app: listmonk
        openova.io/tenant: "aaa"
    spec:
      initContainers:
        - name: listmonk-init
          image: listmonk/listmonk:latest
          command: ["sh", "-c"]
          args: ["./listmonk --install --yes --idempotent 2>&1 || ./listmonk --upgrade --yes 2>&1 || true"]
          env:
            - name: LISTMONK_db__host
              value: "postgres"
            - name: LISTMONK_db__port
              value: "5432"
            - name: LISTMONK_db__user
              value: "app"
            - name: LISTMONK_db__password
              value: "8bb38a3e15dcd6b40adc619b44a405c9"
            - name: LISTMONK_db__database
              value: "db_listmonk"
            - name: LISTMONK_db__ssl_mode
              value: "disable"
            - name: LISTMONK_db__max_open
              value: "25"
            - name: LISTMONK_db__max_idle
              value: "25"
            - name: LISTMONK_db__max_lifetime
              value: "300s"
      containers:
        - name: listmonk
          image: listmonk/listmonk:latest
          ports:
            - containerPort: 9000
          env:
            - name: LISTMONK_db__host
              value: "postgres"
            - name: LISTMONK_db__port
              value: "5432"
            - name: LISTMONK_db__user
              value: "app"
            - name: LISTMONK_db__password
              value: "8bb38a3e15dcd6b40adc619b44a405c9"
            - name: LISTMONK_db__database
              value: "db_listmonk"
            - name: LISTMONK_db__ssl_mode
              value: "disable"
            - name: LISTMONK_db__max_open
              value: "25"
            - name: LISTMONK_db__max_idle
              value: "25"
            - name: LISTMONK_db__max_lifetime
              value: "300s"
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: listmonk
  namespace: apps
spec:
  selector:
    app: listmonk
  ports:
    - port: 80
      targetPort: 9000
