// identity_keyset_test.go — UAT rows 212 + 213 regression lock.
//
// Rows 212/213 assert Org-boundary behaviour on the MCP (212: an Org-scoped
// token lists only that Org's apps; 213: a cross-Org get_application answers
// 403). On hw293 NEITHER clause could be evaluated, because an Org-scoped
// bearer never gets past AUTHENTICATION:
//
//	-32001 unauthenticated — identity: bearer rejected:
//	token signature is invalid: crypto/rsa: verification error   (3/3)
//
// with two controls run in the same minutes: the byte-identical string is
// ACCEPTED by catalyst-api itself (GET /whoami → 200, orgScoped:true), and a
// sovereign-scoped session is accepted by the SAME MCP 3/3, interleaved.
//
// The MCP verifies against exactly ONE pinned RSA public key
// (NewRS256Resolver). A Sovereign does not have one signer — it has a SET:
//
//   - the MOTHERSHIP-injected handover key in `catalyst-handover-jwt-public`,
//     which #4450's decidePubkeyPublish deliberately PRESERVES on a Sovereign
//     (overwriting it 401s every inbound owner handover), and
//   - the Sovereign catalyst-api's OWN handoverjwt signer, self-generated by
//     LoadOrGenerate, which signs every session bearer it mints
//     (HandlePinVerify, org_handover, org_enter_org, sovereign_mcp_bearer_seed)
//     — one per catalyst-api Pod whose key file is on its own RWO PVC.
//
// catalyst-api already solved this for itself: auth_handover.go collects a
// CANDIDATE LIST (#4101 — "the keyfunc tries the mounted key first, then the
// local one") after verifying-with-one-key rejected every Enter-org token with
// the identical `crypto/rsa: verification error`. The MCP never got the same
// treatment, and #5175 filed exactly this ("have the MCP accept both keys — a
// small JWKS/multi-key verify") as a design option that was never implemented.
//
// This lock asserts the MCP verifies against a SET, and — the half that keeps
// it from being a licence to accept anything — that a token signed by a key
// OUTSIDE the set is still refused.
package identity

import (
	"crypto/rand"
	"crypto/rsa"
	"strings"
	"testing"
	"time"

	"github.com/golang-jwt/jwt/v5"
)

func mustKey(t *testing.T) *rsa.PrivateKey {
	t.Helper()
	k, err := rsa.GenerateKey(rand.Reader, 2048)
	if err != nil {
		t.Fatalf("generate key: %v", err)
	}
	return k
}

// signOrgScoped mints the EXACT claim shape catalyst-api's HandlePinVerify
// stamps for an Org-scoped customer session on console.<org>.<pool>
// (tier=org-admin, role=openova-user, typ=session, org_id=<slug>), RS256.
func signOrgScoped(t *testing.T, k *rsa.PrivateKey, org string) string {
	t.Helper()
	now := time.Now()
	tok := jwt.NewWithClaims(jwt.SigningMethodRS256, jwt.MapClaims{
		"iss": "https://console.hw293.omantel.biz", "sub": "walker@openova.io",
		"email": "walker@openova.io", "email_verified": true,
		"role": "openova-user", "tier": "org-admin", "typ": "session",
		"org": org, "org_id": org,
		"iat": now.Unix(), "exp": now.Add(time.Hour).Unix(),
	})
	s, err := tok.SignedString(k)
	if err != nil {
		t.Fatalf("sign: %v", err)
	}
	return s
}

// signSovereign mints a sovereign-admin session — the CONTROL token, which was
// accepted 3/3 on hw293 and must keep being accepted.
func signSovereign(t *testing.T, k *rsa.PrivateKey) string {
	t.Helper()
	now := time.Now()
	tok := jwt.NewWithClaims(jwt.SigningMethodRS256, jwt.MapClaims{
		"iss": "https://console.hw293.omantel.biz", "sub": "walker@openova.io",
		"email": "walker@openova.io", "role": "sovereign-admin", "typ": "session",
		"deployment_id": "a0077ba47e3720e5",
		"iat":           now.Unix(), "exp": now.Add(time.Hour).Unix(),
	})
	s, err := tok.SignedString(k)
	if err != nil {
		t.Fatalf("sign: %v", err)
	}
	return s
}

// TestRS256Set_AcceptsEitherSignerAndRefusesAnyOther is the row-212/213 lock.
func TestRS256Set_AcceptsEitherSignerAndRefusesAnyOther(t *testing.T) {
	mothership := mustKey(t) // the injected catalyst-handover-jwt-public key
	local := mustKey(t)      // the Sovereign catalyst-api's own session signer
	stranger := mustKey(t)   // no relationship to this Sovereign

	// A Sovereign-mode instance pins ContextSovereign, which #5206 makes reject
	// an Org-scoped token AFTER the signature check. Rows 212/213 are about the
	// Org surface, so the instance under test is the Org-context one — the same
	// resolver code, the pin that admits an org_id token.
	r := NewRS256SetResolver([]*rsa.PublicKey{&mothership.PublicKey, &local.PublicKey}, ContextOrganization)

	t.Run("org-scoped bearer signed by the LOCAL session signer is accepted", func(t *testing.T) {
		id, err := r.Resolve("Bearer " + signOrgScoped(t, local, "hw293walkone"))
		if err != nil {
			t.Fatalf("org-scoped bearer rejected: %v", err)
		}
		// Assert the resolved VALUES, not merely that no error came back.
		if id.Context != ContextOrganization {
			t.Errorf("context = %q, want %q", id.Context, ContextOrganization)
		}
		if id.OrgID != "hw293walkone" {
			t.Errorf("orgID = %q, want %q", id.OrgID, "hw293walkone")
		}
		if id.Tier != TierAdmin {
			t.Errorf("tier = %v, want %v (org-admin is the admin of its OWN Org)", id.Tier, TierAdmin)
		}
	})

	t.Run("CONTROL — a bearer signed by the MOTHERSHIP key is still accepted", func(t *testing.T) {
		if _, err := r.Resolve("Bearer " + signOrgScoped(t, mothership, "hw293walkone")); err != nil {
			t.Fatalf("mothership-signed bearer rejected — the fix dropped a key it used to trust: %v", err)
		}
	})

	t.Run("CONTROL — a bearer signed by a key OUTSIDE the set is REFUSED", func(t *testing.T) {
		_, err := r.Resolve("Bearer " + signOrgScoped(t, stranger, "hw293walkone"))
		if err == nil {
			t.Fatal("a token signed by an untrusted key was ACCEPTED — the resolver stopped verifying")
		}
		if !strings.Contains(err.Error(), "signature is invalid") {
			t.Errorf("rejection reason = %q, want a signature failure", err.Error())
		}
	})

	t.Run("CONTROL — a tampered payload under a trusted key is REFUSED", func(t *testing.T) {
		raw := signOrgScoped(t, local, "hw293walkone")
		parts := strings.Split(raw, ".")
		// Flip one byte of the payload; the signature no longer covers it.
		body := []byte(parts[1])
		body[0] ^= 0x01
		if _, err := r.Resolve("Bearer " + parts[0] + "." + string(body) + "." + parts[2]); err == nil {
			t.Fatal("a tampered token was ACCEPTED")
		}
	})

	t.Run("CONTROL — an HS256 token is REFUSED even with a matching-shaped payload", func(t *testing.T) {
		now := time.Now()
		hs := jwt.NewWithClaims(jwt.SigningMethodHS256, jwt.MapClaims{
			"tier": "org-admin", "org_id": "hw293walkone",
			"iat": now.Unix(), "exp": now.Add(time.Hour).Unix(),
		})
		s, err := hs.SignedString([]byte("not-the-rsa-key"))
		if err != nil {
			t.Fatal(err)
		}
		if _, err := r.Resolve("Bearer " + s); err == nil {
			t.Fatal("an HS256 token was accepted by an rs256 resolver")
		}
	})
}

// TestRS256Set_SovereignControlTokenStillResolves is the interleaved control
// from the hw293 walk: the sovereign session that was accepted 3/3 must keep
// resolving to the Sovereign context on a Sovereign-mode instance.
func TestRS256Set_SovereignControlTokenStillResolves(t *testing.T) {
	mothership := mustKey(t)
	local := mustKey(t)
	r := NewRS256SetResolver([]*rsa.PublicKey{&mothership.PublicKey, &local.PublicKey}, ContextSovereign)

	id, err := r.Resolve("Bearer " + signSovereign(t, local))
	if err != nil {
		t.Fatalf("sovereign control token rejected: %v", err)
	}
	if id.Context != ContextSovereign {
		t.Errorf("context = %q, want %q", id.Context, ContextSovereign)
	}
	if id.Tier != TierSovereignAdmin {
		t.Errorf("tier = %v, want %v", id.Tier, TierSovereignAdmin)
	}
}

// TestNewRS256Resolver_SingleKeyIsStillOneElementSet keeps the pre-existing
// single-key constructor honest — every existing caller and test must behave
// exactly as before.
func TestNewRS256Resolver_SingleKeyIsStillOneElementSet(t *testing.T) {
	a := mustKey(t)
	b := mustKey(t)
	r := NewRS256Resolver(&a.PublicKey, ContextOrganization)

	if _, err := r.Resolve("Bearer " + signOrgScoped(t, a, "acme")); err != nil {
		t.Fatalf("single-key resolver rejected its own key's token: %v", err)
	}
	if _, err := r.Resolve("Bearer " + signOrgScoped(t, b, "acme")); err == nil {
		t.Fatal("single-key resolver accepted a foreign key's token")
	}
}

// TestRS256Set_EmptySetIsNotAnOpenDoor — a set that ended up empty must refuse
// everything rather than skip verification. Without this, a mis-wired Secret
// would silently become verify=insecure.
func TestRS256Set_EmptySetIsNotAnOpenDoor(t *testing.T) {
	a := mustKey(t)
	r := NewRS256SetResolver(nil, ContextOrganization)
	if _, err := r.Resolve("Bearer " + signOrgScoped(t, a, "acme")); err == nil {
		t.Fatal("a resolver with NO verify keys accepted a bearer")
	}
}
