package handlers

// Tests for voucher-code entropy (#3376 DoD-6).

import (
	"strings"
	"testing"
)

func TestGenerateVoucherCode_ShapeAndEntropy(t *testing.T) {
	seen := map[string]bool{}
	for i := 0; i < 500; i++ {
		code, err := generateVoucherCode()
		if err != nil {
			t.Fatalf("generateVoucherCode: %v", err)
		}
		if !strings.HasPrefix(code, "VCH-") {
			t.Fatalf("code %q missing VCH- prefix", code)
		}
		body := strings.TrimPrefix(code, "VCH-")
		if len(body) != 12 {
			t.Fatalf("code body %q len = %d, want 12", body, len(body))
		}
		for _, r := range body {
			if !strings.ContainsRune(voucherCodeAlphabet, r) {
				t.Fatalf("code %q contains char %q outside the unambiguous alphabet", code, r)
			}
		}
		// A generated code must itself pass the strength gate.
		if err := validateVoucherCodeStrength(code); err != nil {
			t.Fatalf("generated code %q failed strength check: %v", code, err)
		}
		if seen[code] {
			t.Fatalf("duplicate generated code %q within 500 draws — entropy too low", code)
		}
		seen[code] = true
	}
}

func TestValidateVoucherCodeStrength(t *testing.T) {
	cases := []struct {
		name    string
		code    string
		wantErr bool
	}{
		// 12 chars, 10 distinct → clears the distinct-char floor. The walk's
		// real hardening is the auto-generate DEFAULT; this floor only
		// blocks the trivially-predictable shapes below.
		{"WALKMART2026-passes-floor", "WALKMART2026", false},
		{"too-short", "ABC123", true},
		{"all-distinct-letters-ok", "ABCDEFGHJKMN", false}, // 12 distinct chars → strong enough
		{"single-repeat", "AAAAAAAAAAAA", true},            // 1 distinct char → rejected
		{"low-distinct-pattern", "ABABABABABAB", true},     // 2 distinct chars → rejected
		{"sequential-digits-repeat", "121212121212", true}, // 2 distinct chars → rejected
		{"strong-generated-shape", "VCH-23456789ABCD", false},
		{"empty-rejected-here", "", true}, // empty is auto-generated by the caller, not validated; direct validation rejects it as too short
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			err := validateVoucherCodeStrength(tc.code)
			if tc.wantErr && err == nil {
				t.Errorf("code %q: expected error, got nil", tc.code)
			}
			if !tc.wantErr && err != nil {
				t.Errorf("code %q: unexpected error: %v", tc.code, err)
			}
		})
	}
}
