// signer_jwks_publish_test.go — UAT rows 212/213, producer half.
//
// `public.jwk` holds exactly ONE key and decidePubkeyPublish guarantees at most
// one signer's key ever occupies it on a Sovereign (#4450 preserves the
// mothership-injected inbound-handover key there). Every bearer a caller
// actually presents, however, is signed by a catalyst-api's OWN handoverjwt
// signer — self-generated by LoadOrGenerate from a key file on a per-Pod RWO
// PVC, so a multi-region Sovereign has one per catalyst-api and none of them
// can take `public.jwk` without breaking owner handover.
//
// mergeSignerJWKS is the additive set the off-pod verifiers read instead.
package main

import (
	"encoding/json"
	"testing"
)

func keysIn(t *testing.T, doc []byte) []string {
	t.Helper()
	var parsed struct {
		Keys []map[string]any `json:"keys"`
	}
	if err := json.Unmarshal(doc, &parsed); err != nil {
		t.Fatalf("result is not a JWKS document: %v (%s)", err, string(doc))
	}
	out := make([]string, 0, len(parsed.Keys))
	for _, k := range parsed.Keys {
		n, _ := k["n"].(string)
		out = append(out, n)
	}
	return out
}

func jwk(n string) []byte {
	return []byte(`{"kty":"RSA","use":"sig","alg":"RS256","n":"` + n + `","e":"AQAB"}`)
}

func TestMergeSignerJWKS_AccumulatesEverySignerOnTheSovereign(t *testing.T) {
	// Boot 1: region-A catalyst-api seeds the set with the mothership key it
	// found on `public.jwk`, then adds its own.
	seeded, changed, err := mergeSignerJWKS(nil, jwk("mothership"))
	if err != nil || !changed {
		t.Fatalf("seed: changed=%v err=%v", changed, err)
	}
	regionA, changed, err := mergeSignerJWKS(seeded, jwk("region-a"))
	if err != nil || !changed {
		t.Fatalf("region-a: changed=%v err=%v", changed, err)
	}
	// Boot 2: region-B catalyst-api adds its own key without displacing either.
	regionB, changed, err := mergeSignerJWKS(regionA, jwk("region-b"))
	if err != nil || !changed {
		t.Fatalf("region-b: changed=%v err=%v", changed, err)
	}

	got := keysIn(t, regionB)
	want := []string{"mothership", "region-a", "region-b"}
	if len(got) != len(want) {
		t.Fatalf("published set = %v, want %v", got, want)
	}
	for i := range want {
		if got[i] != want[i] {
			t.Fatalf("published set = %v, want %v", got, want)
		}
	}
}

// CONTROL — re-publishing an already-present key is a no-op. Without this the
// Secret would be PATCHed on every Pod boot, bouncing Reloader and every
// consumer that watches it.
func TestMergeSignerJWKS_IdempotentOnRepublish(t *testing.T) {
	doc, _, _ := mergeSignerJWKS(nil, jwk("region-a"))
	again, changed, err := mergeSignerJWKS(doc, jwk("region-a"))
	if err != nil {
		t.Fatal(err)
	}
	if changed {
		t.Fatal("re-publishing the same key reported a change")
	}
	if string(again) != string(doc) {
		t.Fatalf("document mutated on a no-op merge: %s -> %s", doc, again)
	}
}

// CONTROL — `use`/`alg`/`kid` noise must not create a duplicate entry. Identity
// is the (n, e) pair, which IS the key.
func TestMergeSignerJWKS_IdentityIsTheKeyNotItsMetadata(t *testing.T) {
	doc, _, _ := mergeSignerJWKS(nil, jwk("region-a"))
	_, changed, err := mergeSignerJWKS(doc, []byte(`{"kty":"RSA","kid":"other","n":"region-a","e":"AQAB"}`))
	if err != nil {
		t.Fatal(err)
	}
	if changed {
		t.Fatal("the same key with different metadata was added a second time")
	}
}

// CONTROL — a corrupt existing mirror must not permanently wedge publication.
func TestMergeSignerJWKS_CorruptExistingIsReplacedNotPropagated(t *testing.T) {
	doc, changed, err := mergeSignerJWKS([]byte("}{ not json"), jwk("region-a"))
	if err != nil || !changed {
		t.Fatalf("changed=%v err=%v", changed, err)
	}
	if got := keysIn(t, doc); len(got) != 1 || got[0] != "region-a" {
		t.Fatalf("recovered set = %v, want [region-a]", got)
	}
}

// CONTROL — the set is BOUNDED. A wiped PVC regenerates the keypair on every
// boot; without a cap the Secret grows until it is rejected.
func TestMergeSignerJWKS_BoundedOldestDroppedFirst(t *testing.T) {
	var doc []byte
	for i := 0; i < maxPublishedSigners+3; i++ {
		var err error
		doc, _, err = mergeSignerJWKS(doc, jwk(string(rune('a'+i))))
		if err != nil {
			t.Fatal(err)
		}
	}
	got := keysIn(t, doc)
	if len(got) != maxPublishedSigners {
		t.Fatalf("set size = %d, want the %d cap", len(got), maxPublishedSigners)
	}
	if got[0] == "a" {
		t.Fatal("the oldest entry survived the cap — newest keys are the ones that must be kept")
	}
	if got[len(got)-1] != string(rune('a'+maxPublishedSigners+2)) {
		t.Fatalf("newest entry missing from a capped set: %v", got)
	}
}

// CONTROL — a key with no n/e is REFUSED rather than silently appended. An
// entry the verifier cannot use must never enter the published set.
func TestMergeSignerJWKS_RefusesAKeyWithNoModulus(t *testing.T) {
	if _, _, err := mergeSignerJWKS(nil, []byte(`{"kty":"RSA"}`)); err == nil {
		t.Fatal("a JWK with no n/e was accepted into the published set")
	}
	if _, _, err := mergeSignerJWKS(nil, []byte("not json")); err == nil {
		t.Fatal("a non-JSON key was accepted into the published set")
	}
}

// CONTROL — decidePubkeyPublish is UNCHANGED. The signer set is additive; the
// #4450 preserve rule for `public.jwk` must still hold, or every inbound owner
// handover 401s again.
func TestDecidePubkeyPublish_SovereignStillPreservesInjectedKey(t *testing.T) {
	if got := decidePubkeyPublish(jwk("local"), jwk("mothership"), true); got != pubkeyPublishPreserveInjected {
		t.Fatalf("Sovereign with an injected key: decision = %v, want preserve", got)
	}
	if got := decidePubkeyPublish(jwk("local"), nil, true); got != pubkeyPublishWrite {
		t.Fatalf("Sovereign with an EMPTY secret: decision = %v, want write", got)
	}
	if got := decidePubkeyPublish(jwk("local"), jwk("stale"), false); got != pubkeyPublishWrite {
		t.Fatalf("mothership with a stale mirror: decision = %v, want write", got)
	}
	if got := decidePubkeyPublish(jwk("local"), jwk("local"), true); got != pubkeyPublishAlreadyCurrent {
		t.Fatalf("already-current: decision = %v, want already-current", got)
	}
}

// TestPublishedSecret_OffPodVerifierCanObtainEverySigner models the WHOLE
// publish path across a multi-region Sovereign's boots and asks the question
// the MCP asks: can an off-pod verifier obtain every key that signs bearers
// here?
//
// Against the pre-fix path this is unanswerable — decidePubkeyPublish returns
// preserveInjected for BOTH catalyst-api Pods, so `public.jwk` keeps the
// mothership key forever and neither session signer's key is published
// anywhere. That is UAT rows 212/213: `crypto/rsa: verification error`, 3/3,
// against a bearer catalyst-api itself answers 200 for.
func TestPublishedSecret_OffPodVerifierCanObtainEverySigner(t *testing.T) {
	mothership, regionA, regionB := jwk("mothership"), jwk("region-a"), jwk("region-b")

	// The Secret as cloud-init leaves it: public.jwk = the injected mothership
	// key, no signer set yet.
	publicJWK := mothership
	var signersJWKS []byte

	// Each catalyst-api boot runs the same two steps publishHandoverPubkey now
	// runs: fold this signer into the additive set, then apply the UNCHANGED
	// #4450 decision to public.jwk.
	boot := func(t *testing.T, own []byte) {
		t.Helper()
		base := signersJWKS
		if seeded, changed, err := mergeSignerJWKS(base, publicJWK); err == nil && changed {
			base = seeded
		}
		merged, _, err := mergeSignerJWKS(base, own)
		if err != nil {
			t.Fatalf("merge: %v", err)
		}
		signersJWKS = merged
		if decidePubkeyPublish(own, publicJWK, true) == pubkeyPublishWrite {
			publicJWK = own
		}
	}
	boot(t, regionA)
	boot(t, regionB)

	// #4450 must be intact: the inbound-handover key is still the one on
	// public.jwk, or every owner handover 401s.
	if string(publicJWK) != string(mothership) {
		t.Fatalf("public.jwk was clobbered (#4450): %s", publicJWK)
	}

	// And the verify SET now covers every signer on this Sovereign.
	got := keysIn(t, signersJWKS)
	for _, want := range []string{"mothership", "region-a", "region-b"} {
		found := false
		for _, g := range got {
			if g == want {
				found = true
			}
		}
		if !found {
			t.Errorf("off-pod verifier cannot obtain the %q signer key; published set = %v", want, got)
		}
	}
}
