apiVersion: apps/v1
kind: Deployment
metadata:
  name: domain
  namespace: sme
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sme-domain
  template:
    metadata:
      labels:
        app: sme-domain
    spec:
      serviceAccountName: domain
      automountServiceAccountToken: false
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: domain
          image: ghcr.io/openova-io/openova-private/sme-domain:635eec7
          imagePullPolicy: Always
          ports:
            - containerPort: 8086
          env:
            - name: MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  name: sme-services-config
                  key: MONGODB_URI
            - name: MONGODB_DB
              value: "domains"
            - name: REDPANDA_BROKERS
              valueFrom:
                configMapKeyRef:
                  name: sme-services-config
                  key: REDPANDA_BROKERS
            - name: CORS_ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: sme-services-config
                  key: CORS_ORIGIN_PUBLIC
            - name: CNAME_TARGET
              valueFrom:
                configMapKeyRef:
                  name: sme-services-config
                  key: CNAME_TARGET
            - name: TENANT_URL
              valueFrom:
                configMapKeyRef:
                  name: sme-services-config
                  key: TENANT_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: sme-secrets
                  key: JWT_SECRET
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 500m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8086
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8086
            initialDelaySeconds: 3
            periodSeconds: 5
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 65534
---
apiVersion: v1
kind: Service
metadata:
  name: domain
  namespace: sme
spec:
  selector:
    app: sme-domain
  ports:
    - port: 8086
      targetPort: 8086
