{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bp-wordpress-tenant.serviceAccountName" . }}
  labels:
    {{- include "bp-wordpress-tenant.labels" . | nindent 4 }}
{{- end }}
