{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bp-coraza.serviceAccountName" . }}
  labels:
    {{- include "bp-coraza.labels" . | nindent 4 }}
{{- end }}
