{{- if .Values.controllers.useraccess.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "controllers.fullname" "useraccess" }}
  labels:
    {{- include "controllers.labels" (dict "name" "useraccess" "root" .) | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "controllers.fullname" "useraccess" }}
subjects:
  - kind: ServiceAccount
    name: {{ include "controllers.fullname" "useraccess" }}
    namespace: {{ .Release.Namespace }}
{{- end }}
