export const HETZNER_NODE_SIZES = [
  {
    id: 'cx22' as const,
    label: 'CX22',
    vcpu: 2,
    ram: 4,
    disk: 40,
    priceHour: 0.007,
    priceMonth: 3.92,
    description: 'Entry — experiments & dev',
    recommended: true,
  },
  {
    id: 'cx32' as const,
    label: 'CX32',
    vcpu: 4,
    ram: 8,
    disk: 80,
    priceHour: 0.014,
    priceMonth: 7.85,
    description: 'Standard — small workloads',
    recommended: false,
  },
  {
    id: 'cx42' as const,
    label: 'CX42',
    vcpu: 8,
    ram: 16,
    disk: 160,
    priceHour: 0.025,
    priceMonth: 16.08,
    description: 'Performance — production',
    recommended: false,
  },
  {
    id: 'cx52' as const,
    label: 'CX52',
    vcpu: 16,
    ram: 32,
    disk: 320,
    priceHour: 0.048,
    priceMonth: 32.16,
    description: 'High-Memory — heavy workloads',
    recommended: false,
  },
] as const

export const HETZNER_REGIONS = [
  { id: 'fsn1', name: 'Falkenstein', location: 'Germany', flag: '🇩🇪', zone: 'eu-central' },
  { id: 'nbg1', name: 'Nuremberg', location: 'Germany', flag: '🇩🇪', zone: 'eu-central' },
  { id: 'hel1', name: 'Helsinki', location: 'Finland', flag: '🇫🇮', zone: 'eu-north' },
  { id: 'ash', name: 'Ashburn', location: 'Virginia, USA', flag: '🇺🇸', zone: 'us-east' },
  { id: 'hil', name: 'Hillsboro', location: 'Oregon, USA', flag: '🇺🇸', zone: 'us-west' },
  { id: 'sin', name: 'Singapore', location: 'Singapore', flag: '🇸🇬', zone: 'ap-southeast' },
] as const
