// organization_gitops_cutover_aware_5527_test.go — #5527: the org-tenant
// pipeline's shared HelmRepository emission must be cutover-aware.
//
// Live failure (hw291, dep 2c2d746b578c636b): cutover step-06 patched the
// per-Org HelmRepositories to the local Harbor, but this generator's git
// source (clusters/<fqdn>/org-tenants/helmrepositories.yaml) still
// declared oci://ghcr.io/openova-io, so Flux drift-corrected the objects
// straight back and the step-08 deny-egress hold failed
// (OFFENDER bp-agenity/bp-openclaw/bp-stalwart-tenant/
// bp-wordpress-tenant=oci://ghcr.io/openova-io). The durable fix: once
// the step-07 pivot fact is readable in-process, the generator emits the
// Sovereign-local registry base itself — one writer, no fight.
//
// Every test here asserts BOTH directions (wanted-present AND
// unwanted-absent) with occurrence counts against the block count, so a
// silently-no-op'd ReplaceAll (e.g. after a drift in the template's URL
// line) can never pass vacuously.
package handler

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// clearCutoverEnv isolates each test from ambient process env for every
// seam the resolver reads.
func clearCutoverEnv(t *testing.T) {
	t.Helper()
	for _, k := range []string{
		"CATALYST_PIN_ISSUER",
		"CATALYST_HANDOVER_JWT_ISSUER",
		"CATALYST_LOCAL_REGISTRY_URL",
		"SOVEREIGN_FQDN",
		"CATALYST_OTECH_FQDN",
	} {
		t.Setenv(k, "")
	}
}

// hrBlockCount returns the number of HelmRepository blocks in the
// rendered document — the denominator every URL/secretRef count is
// checked against.
func hrBlockCount(doc string) int {
	return strings.Count(doc, "kind: HelmRepository")
}

// TestOrgTenantHelmRepositories_PreCutoverEmitsGHCR — pre-cutover (no
// step-07 fact) the emission is byte-identical to the historical
// template: every block declares the public ghcr catalog. A Sovereign
// identity ALONE (SOVEREIGN_FQDN set — true from birth on every chroot)
// must NOT flip the URL: pre-cutover the local Harbor holds no charts.
func TestOrgTenantHelmRepositories_PreCutoverEmitsGHCR(t *testing.T) {
	clearCutoverEnv(t)
	t.Setenv("SOVEREIGN_FQDN", "hw291.omantel.biz")

	got := orgTenantSharedHelmRepositoriesYAML()
	if got != orgTenantSharedHelmRepositories {
		t.Fatalf("pre-cutover emission must be byte-identical to the template (zero Flux drift), diff detected:\n%s", got)
	}

	blocks := hrBlockCount(got)
	if blocks == 0 {
		t.Fatal("vacuity check failed: rendered document contains no HelmRepository blocks at all")
	}
	ghcr := strings.Count(got, "url: "+orgTenantGHCRBase)
	if ghcr != blocks {
		t.Fatalf("pre-cutover: want every block on the ghcr base, got %d ghcr url lines across %d blocks:\n%s", ghcr, blocks, got)
	}
	if strings.Contains(got, "registry.hw291.omantel.biz") {
		t.Fatalf("pre-cutover: local registry host leaked into the emission:\n%s", got)
	}
}

// TestOrgTenantHelmRepositories_PostCutoverEmitsLocalRegistry — with the
// step-07 issuer fact stamped, EVERY block pivots to
// oci://registry.<fqdn>/openova-io (the exact shape step-06 patches the
// live objects to — hw291 remediation value), no ghcr url line survives,
// and secretRef stays ghcr-pull on every block (the cutover rewrites
// that Secret's contents, not its name).
func TestOrgTenantHelmRepositories_PostCutoverEmitsLocalRegistry(t *testing.T) {
	clearCutoverEnv(t)
	t.Setenv("CATALYST_PIN_ISSUER", "https://console.hw291.omantel.biz")
	t.Setenv("CATALYST_HANDOVER_JWT_ISSUER", "https://console.hw291.omantel.biz")
	t.Setenv("SOVEREIGN_FQDN", "hw291.omantel.biz")

	got := orgTenantSharedHelmRepositoriesYAML()
	blocks := hrBlockCount(got)
	if blocks == 0 {
		t.Fatal("vacuity check failed: rendered document contains no HelmRepository blocks at all")
	}
	local := strings.Count(got, "url: oci://registry.hw291.omantel.biz/openova-io")
	if local != blocks {
		t.Fatalf("post-cutover: want every block on the local base, got %d local url lines across %d blocks:\n%s", local, blocks, got)
	}
	if strings.Contains(got, "url: "+orgTenantGHCRBase) {
		t.Fatalf("post-cutover: a ghcr url line survived — the #5527 re-tether:\n%s", got)
	}
	pull := strings.Count(got, "name: ghcr-pull")
	if pull != blocks {
		t.Fatalf("post-cutover: secretRef ghcr-pull must be retained on every block (step-06 parity), got %d across %d blocks:\n%s", pull, blocks, got)
	}
	// The DO-NOT-EDIT header must still open the document so operators
	// keep the regenerate warning, now with the cutover-aware note.
	if !strings.HasPrefix(got, "# Generated by catalyst-api/org-tenant pipeline (#893).") {
		t.Fatalf("post-cutover: generated header lost:\n%s", got)
	}
	if !strings.Contains(got, "cutover-aware (#5527)") {
		t.Fatalf("header must carry the cutover-aware note (#5527):\n%s", got)
	}
}

// TestOrgTenantHelmRepositories_HandoverIssuerAloneFlips — the two
// issuer envs are stamped in ONE step-07 `kubectl set env`, but the fact
// reader tolerates a partial state: either var alone is the fact.
func TestOrgTenantHelmRepositories_HandoverIssuerAloneFlips(t *testing.T) {
	clearCutoverEnv(t)
	t.Setenv("CATALYST_HANDOVER_JWT_ISSUER", "https://console.hw291.omantel.biz")
	t.Setenv("SOVEREIGN_FQDN", "hw291.omantel.biz")

	got := orgTenantHelmRepositoryURL()
	want := "oci://registry.hw291.omantel.biz/openova-io"
	if got != want {
		t.Fatalf("handover-JWT issuer alone must flip the base: got %q want %q", got, want)
	}
}

// TestOrgTenantHelmRepositories_OTECHFQDNSynonym — chroot pods where only
// CATALYST_OTECH_FQDN is stamped resolve the same host (the
// sovereign_self.go synonym order).
func TestOrgTenantHelmRepositories_OTECHFQDNSynonym(t *testing.T) {
	clearCutoverEnv(t)
	t.Setenv("CATALYST_PIN_ISSUER", "https://console.hw291.omantel.biz")
	t.Setenv("CATALYST_OTECH_FQDN", "hw291.omantel.biz")

	got := orgTenantHelmRepositoryURL()
	want := "oci://registry.hw291.omantel.biz/openova-io"
	if got != want {
		t.Fatalf("CATALYST_OTECH_FQDN synonym must resolve the host: got %q want %q", got, want)
	}
}

// TestOrgTenantHelmRepositories_FactWithoutIdentityFailsSafe — the pivot
// fact without any Sovereign FQDN cannot mint a registry host; the
// generator must fail SAFE to the public catalog rather than emit
// oci://registry./openova-io.
func TestOrgTenantHelmRepositories_FactWithoutIdentityFailsSafe(t *testing.T) {
	clearCutoverEnv(t)
	t.Setenv("CATALYST_PIN_ISSUER", "https://console.hw291.omantel.biz")

	if got := orgTenantHelmRepositoryURL(); got != orgTenantGHCRBase {
		t.Fatalf("fact without identity must fall back to ghcr, got %q", got)
	}
	if doc := orgTenantSharedHelmRepositoriesYAML(); doc != orgTenantSharedHelmRepositories {
		t.Fatalf("fact without identity must emit the unmodified template:\n%s", doc)
	}
}

// TestOrgTenantHelmRepositories_ExplicitOverrideWins — a non-empty
// CATALYST_LOCAL_REGISTRY_URL is authoritative on its own (Principle #4:
// a future step-07 stamping the exact value flips the generator with no
// issuer heuristic involved), and is normalised to a clean oci:// base.
func TestOrgTenantHelmRepositories_ExplicitOverrideWins(t *testing.T) {
	cases := []struct {
		name, override, want string
	}{
		{"full-oci-base", "oci://registry.hw291.omantel.biz/openova-io", "oci://registry.hw291.omantel.biz/openova-io"},
		{"missing-scheme", "registry.hw291.omantel.biz/openova-io", "oci://registry.hw291.omantel.biz/openova-io"},
		{"trailing-slash", "oci://registry.hw291.omantel.biz/openova-io/", "oci://registry.hw291.omantel.biz/openova-io"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			clearCutoverEnv(t)
			// Deliberately NO issuer fact and NO FQDN — the override
			// alone must flip.
			t.Setenv("CATALYST_LOCAL_REGISTRY_URL", tc.override)
			if got := orgTenantHelmRepositoryURL(); got != tc.want {
				t.Fatalf("override %q: got %q want %q", tc.override, got, tc.want)
			}
			doc := orgTenantSharedHelmRepositoriesYAML()
			blocks := hrBlockCount(doc)
			if blocks == 0 {
				t.Fatal("vacuity check failed: no HelmRepository blocks rendered")
			}
			if n := strings.Count(doc, "url: "+tc.want); n != blocks {
				t.Fatalf("override emission: got %d local url lines across %d blocks:\n%s", n, blocks, doc)
			}
			if strings.Contains(doc, "url: "+orgTenantGHCRBase) {
				t.Fatalf("override emission: a ghcr url line survived:\n%s", doc)
			}
		})
	}
}

// TestWriteParentTenantsIndex_PostCutoverFileCarriesLocalURL — the
// actual file-write path (writeParentTenantsIndex) must land the pivoted
// bytes on disk, proving the wiring from resolver to os.WriteFile — the
// exact leg that regenerates clusters/<fqdn>/org-tenants/
// helmrepositories.yaml on every org mutation and re-tethered hw291.
func TestWriteParentTenantsIndex_PostCutoverFileCarriesLocalURL(t *testing.T) {
	clearCutoverEnv(t)
	t.Setenv("CATALYST_PIN_ISSUER", "https://console.hw291.omantel.biz")
	t.Setenv("SOVEREIGN_FQDN", "hw291.omantel.biz")

	parent := filepath.Join(t.TempDir(), "org-tenants")
	if err := writeParentTenantsIndex(parent); err != nil {
		t.Fatalf("writeParentTenantsIndex: %v", err)
	}
	raw, err := os.ReadFile(filepath.Join(parent, "helmrepositories.yaml"))
	if err != nil {
		t.Fatalf("read helmrepositories.yaml: %v", err)
	}
	doc := string(raw)
	blocks := hrBlockCount(doc)
	if blocks == 0 {
		t.Fatal("vacuity check failed: written file contains no HelmRepository blocks")
	}
	if n := strings.Count(doc, "url: oci://registry.hw291.omantel.biz/openova-io"); n != blocks {
		t.Fatalf("written file: got %d local url lines across %d blocks:\n%s", n, blocks, doc)
	}
	if strings.Contains(doc, "url: "+orgTenantGHCRBase) {
		t.Fatalf("written file: a ghcr url line survived — regeneration would re-tether the Sovereign:\n%s", doc)
	}
}

// TestWriteParentTenantsIndex_PreCutoverFileKeepsGHCR — the same
// file-write path pre-cutover lands the unmodified ghcr template
// (positive control for the pair above: proves the flip is driven by the
// fact, not by the test harness).
func TestWriteParentTenantsIndex_PreCutoverFileKeepsGHCR(t *testing.T) {
	clearCutoverEnv(t)
	t.Setenv("SOVEREIGN_FQDN", "hw291.omantel.biz")

	parent := filepath.Join(t.TempDir(), "org-tenants")
	if err := writeParentTenantsIndex(parent); err != nil {
		t.Fatalf("writeParentTenantsIndex: %v", err)
	}
	raw, err := os.ReadFile(filepath.Join(parent, "helmrepositories.yaml"))
	if err != nil {
		t.Fatalf("read helmrepositories.yaml: %v", err)
	}
	doc := string(raw)
	blocks := hrBlockCount(doc)
	if blocks == 0 {
		t.Fatal("vacuity check failed: written file contains no HelmRepository blocks")
	}
	if n := strings.Count(doc, "url: "+orgTenantGHCRBase); n != blocks {
		t.Fatalf("pre-cutover written file: got %d ghcr url lines across %d blocks:\n%s", n, blocks, doc)
	}
	if strings.Contains(doc, "registry.hw291.omantel.biz") {
		t.Fatalf("pre-cutover written file: local registry host leaked:\n%s", doc)
	}
}
